server:
  port: ${PORT:8765}

spring:
  application:
    name: gateway-server

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE

zuul:
  routes:
    account:
      path: /account/**
      sensitiveHeaders:
      serviceId: accountsserver

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
