server:
  port: ${DISCOVERY_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOST:localhost}
    leaseRenewalIntervalInSeconds: 30 #Registration Time: 30s is the default client refresh time, change this by setting here
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:${HOST:localhost}}:${DISCOVERY_PORT:8761}/eureka/


# https://github.com/Netflix/eureka/wiki/Configuring-Eureka,
# https://spring.io/blog/2015/07/14/microservices-with-spring#accountswebapplication-configuration